server:
  port: 8889

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MrPing
    username: root
    password: 286256

mybatis:
#  ����·��
  mapper-locations: classpath:com/mrping/mapper/*.xml
#  ����mapper����user����ǰ���·��
  type-aliases-package: com.mrping.EntityClass
